### ISSUE TITLE
How to clear selection of tabs ?

### ISSUE THREAD

**Issue by deshario** [ashazar/tab-drawer#3]
How to clear the selection of tabs when i click the others tabs that have sub-items.
if we click the tabs that have sub-items ... the selection of tabs before is not removed. how can i remove it. 
*** If there are not TabListItem ... everythings gonna perfect but we addTabListItem into tabs .. there will be this problem... ***
Thankyou
![screenshot_1508671276](https://user-images.githubusercontent.com/11426727/31861375-7c7cd990-b756-11e7-81d8-edfcf0062d36.png)

**Comment by samita121** [comment]
I wonder to know it too.

**Comment by ashazar** [comment]
When you click on another tab with sub-items, you actually don't select it yet.
That's why the actual (_previous selected_) tab is still kind-of active. `(inactiveSelected)`
So i planned to give it a darker color of selected background color as `inactiveSelected` color

The arguments for the setTabBackgroundColors() and setBackgroundColors() are as follows:
(DEFAULT_COLOR, SELECTED_COLOR, INACTIVE_SELECTED_COLOR)


You can make its _inactiveSelected_ color as the default (unselected) color.

For all Tabs:
```
TabDrawerData
    .setTabBackgroundColors(DEFAULT_COLOR, SELECTED_COLOR, DEFAULT_COLOR);
```

For a specific Tab:
```
Tab
    .setBackgroundColors(DEFAULT_COLOR, SELECTED_COLOR, DEFAULT_COLOR);
```

**Comment by deshario** [comment]
Ok Thankx. It works.

**Comment by deshario** [comment]
When we popBackStackImmediate() all fragments its will be returned to first page... but tab is still selected to previous one. can we implement with onBackPressed() to select first tab.
![backpressed](https://user-images.githubusercontent.com/11426727/31933293-ed49da4c-b8d2-11e7-94d0-bcdf93d3fc33.PNG)

**Comment by ashazar** [comment]
Good catch! Thanks.

I will add a method to select a tab manually, in the coming release.

**Comment by deshario** [comment]
Oh I'm waiting for your new release... because i need to submit my app very soon 😉😉😉

**Comment by ashazar** [comment]
You need to change TabDrawer's version to 1.2.0  in your build.gradle file.
Then you can use `tabDrawer.setSelectedTab(tabPosition, itemPosition, false)`
